spring.application.name=tripping-server
server.port=8080


# Gemini API
gemini.api-key=${GEMINI_API_KEY:}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
gemini.model=${GEMINI_MODEL:gemini-3.6-flash}

# Kakao OAuth API
kakao.rest-api-key=${KAKAO_REST_API_KEY:}
kakao.client-secret=${KAKAO_CLIENT_SECRET:}
kakao.redirect-uri=${KAKAO_REDIRECT_URI:http://localhost:5173/select}

kakao.token-url=${KAKAO_TOKEN_URL:https://kauth.kakao.com/oauth/token}
kakao.user-info-url=${KAKAO_USER_INFO_URL:https://kapi.kakao.com/v2/user/me}

# JWT
jwt.secret=${JWT_SECRET:change-this-secret-in-local}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}

# Tourism API
tourism.api-key=${TOURISM_API_KEY:}
tourism.base-url=${TOURISM_BASE_URL:https://apis.data.go.kr/B551011/KorService2}

# Firebase
firebase.project-id=${FIREBASE_PROJECT_ID:}
firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:}